---

# Monitor Number    = 42
# Ephone 1 Mac Add  = 204c.9e6c.8743
# Ephone 2 Mac Add  = ccd8.c1fb.02b7
#
- name: "Day 1 Config: CUCM"
  hosts: cucm
  gather_facts: no
  become: yes
  tasks:
    - name: "Configuring Console Access"
      ios_command: 
        commands:
          - conf t
          - hostname cucm-42
          - enable secret pass
          - service password-encryption
          - no logging console
          - no ip domain-lookup
          - line cons 0
          - password pass
          - login
          - exec-timeout 0 0
          - exit
          - line vty 0 14
          - password pass
          - login local
          - exec-timeout 0 0
          - end
      tags:
        - accesscli

    - name: "Assigning IP Addresses"
      ios_command:
        commands:
          - conf t
          - int fa0/0
          - no shut
          - ip add 10.42.100.8 255.255.255.0
          - end
      tags:
        - interface
    
    - name: "Configuring Analogue Phones"
      ios_command: 
        commands: 
          - conf t
          - dial-peer voice 1 pots
          - "destination-pattern 4200"
          - port 0/0/0
          - dial-peer voice 2 pots
          - "destination-pattern 4201"
          - port 0/0/1
          - dial-peer voice 3 pots
          - "destination-pattern 4202"
          - port 0/0/2
          - dial-peer voice 4 pots
          - "destination-pattern 4203"
          - port 0/0/3
          - end
      tags:
        - analogue
    
    - name: "Initializing Telephony Service"
      ios_command:
        commands:
          - conf t
          - no telephony-service
          - telephony-service
          - no auto assign
          - no auto-reg-ephone
          - max-ephones 5
          - max-dn 20
          - ip source-address 10.42.100.8 port 2000
          - create cnf-files
          - ephone-dn 1
          - "number 4211"
          - ephone-dn 2
          - "number 4222"
          - ephone-dn 3
          - "number 4233"
          - ephone-dn 4
          - "number 4244"
          - ephone-dn 5
          - "number 4255"
          - ephone-dn 6
          - "number 4266"
          - ephone-dn 7
          - "number 4277"
          - ephone-dn 8
          - "number 4288"
          - ephone 1
          - "mac-address 204c.9e6c.8743"
          - type 8945
          - button 1:1 2:2 3:3 4:4
          - restart
          - ephone 2
          - "mac-address ccd8.c1fb.02b7"
          - type 8945
          - button 1:5 2:6 3:7 4:8
          - restart
          - end
      tags:
        - telephony
    
    - name: "Activating Video Calls"
      ios_command: 
        commands: 
          - conf t
          - "ephone 1"
          - video
          - voice service voip
          - h323
          - call start slow
          - ephone 2
          - video
          - voice service voip
          - h323
          - call start slow
          - end
      tags: 
        - video
    
    - name: "Allowing Incoming Calls"
      ios_command: 
        commands: 
          - conf t
          - voice service voip
          - ip address trusted list
          - ipv4 0.0.0.0 0.0.0.0
          - end
      tags:
        - incoming
    
    - name: "Allowing Outgoing Calls"
      ios_command:
        commands: 
          - conf t
          - dial-peer voice 11 Voip
          - destination-pattern 11..
          - session target ipv4:10.11.100.8
          - codec g711ULAW
          - dial-peer voice 12 Voip
          - destination-pattern 12..
          - session target ipv4:10.12.100.8
          - codec g711ULAW
          - dial-peer voice 21 Voip
          - destination-pattern 21..
          - session target ipv4:10.21.100.8
          - codec g711ULAW
          - dial-peer voice 22 Voip
          - destination-pattern 22..
          - session target ipv4:10.22.100.8
          - codec g711ULAW
          - dial-peer voice 31 Voip
          - destination-pattern 31..
          - session target ipv4:10.31.100.8
          - codec g711ULAW
          - dial-peer voice 42 Voip
          - destination-pattern 42..
          - session target ipv4:10.42.100.8
          - codec g711ULAW
          - dial-peer voice 41 Voip
          - destination-pattern 41..
          - session target ipv4:10.41.100.8
          - codec g711ULAW
          - dial-peer voice 42 Voip
          - destination-pattern 42..
          - session target ipv4:10.42.100.8
          - codec g711ULAW
          - dial-peer voice 51 Voip
          - destination-pattern 51..
          - session target ipv4:10.51.100.8
          - codec g711ULAW
          - dial-peer voice 52 Voip
          - destination-pattern 52..
          - session target ipv4:10.52.100.8
          - codec g711ULAW
          - dial-peer voice 61 Voip
          - destination-pattern 61..
          - session target ipv4:10.61.100.8
          - codec g711ULAW
          - dial-peer voice 62 Voip
          - destination-pattern 62..
          - session target ipv4:10.62.100.8
          - codec g711ULAW
          - dial-peer voice 71 Voip
          - destination-pattern 71..
          - session target ipv4:10.71.100.8
          - codec g711ULAW
          - dial-peer voice 72 Voip
          - destination-pattern 72..
          - session target ipv4:10.72.100.8
          - codec g711ULAW
          - dial-peer voice 81 Voip
          - destination-pattern 81..
          - session target ipv4:10.81.100.8
          - codec g711ULAW
          - dial-peer voice 82 Voip
          - destination-pattern 82..
          - session target ipv4:10.82.100.8
          - codec g711ULAW
          - end
      tags:
        - outgoing
      
    - name: "Assigning a Floating Static Default Route"
      ios_command: 
        commands: 
          - conf t
          - ip routing
          - ip route 0.0.0.0 0.0.0.0 10.42.100.4 254
          - end
      tags: 
        - defroute
    
    - name: "Configuring OSPF"
      ios_command: 
        commands: 
          - conf t
          - router ospf 1
          - router-id 10.42.100.8
          - network 10.42.100.0 0.0.0.255 area 0
          - end
      tags: 
        - ospf
    
    - name: "Register ePhones"
      ios_command:
       commands: 
         - conf t
         - telephony-service
         - create cnf-files
         - end
      tags: 
        - getcnf
